version: '1'
services:
  airlines:
    build: 
      context: ./airlines
    ports:
      - "8080:8080"
  flights:
    build: 
      context: ./flights
    ports:
      - "5001:5001"
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
