apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-app
  template:
    metadata:
      labels:
        app: flight-app
    spec:
      containers:
      - name: flight-app-js
        image: flight-app-js
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
      - name: flight-app-py
        image: flight-app-py
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
